-- 1) WHERE SALES_DATE LIKE '2021-03%'
-- 2) DATE_FORMAT(SALES_DATE, '%Y-%m-%d')
-- 3) DATE(SALES_DATE) => 2020-02-02
SELECT YEAR(B.SALES_DATE) AS YEAR,
       MONTH(B.SALES_DATE) AS MONTH,
       A.GENDER AS GENDER,
       COUNT(DISTINCT A.USER_ID) AS USERS
FROM USER_INFO A JOIN ONLINE_SALE B
ON A.USER_ID = B.USER_ID
WHERE A.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, A.GENDER -- 년, 월, 성별 별로 상품을 구매한 회원수 집계
ORDER BY YEAR, MONTH, A.GENDER;