-- 집계함수(COUNT, SUM, AVG 등)를 제외한 모든 SELECT 컬럼은 반드시 GROUP BY 절에 명시
SELECT
    COUNT(I.ID) AS FISH_COUNT,
    N.FISH_NAME
FROM FISH_INFO AS I
JOIN FISH_NAME_INFO AS N
    ON I.FISH_TYPE = N.FISH_TYPE
GROUP BY I.FISH_TYPE, N.FISH_NAME
ORDER BY FISH_COUNT DESC;