--1. DATETIME vs HOUR
--- DATETIME 초 단위까지 다르기에 그대로 GROUP BY 하면 시간대 별로 묶이지x
--- HOUR(DATETIME)으로 시간만 추출해서 단위 통일
--
--2. SELECT (HOUR, 가공된 시간) == GROUP BY(묶는 기준) 일치

SELECT HOUR(DATETIME) AS HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) BETWEEN 9 AND 19
GROUP BY HOUR
-- HAVING HOUR >= 9 AND HOUR <=19 -- 그룹화 필터링 가능
ORDER BY HOUR ASC; -- ORDER에 별칭