-- ORDER BY ANIMAL_TYPE ASC
-- ORDER BY FIELD(ANIMAL_TYPE, 'CAT', 'DOG') (특정 순서를 강제)
SELECT ANIMAL_TYPE, COUNT(ANIMAL_ID) AS count
FROM ANIMAL_INS
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE='CAT' DESC;