WITH RANKED_ECOLI AS(
    SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS QUARTER
    FROM ECOLI_DATA
)
SELECT ID,
    CASE QUARTER
        WHEN 1 THEN 'CRITICAL'
        WHEN 2 THEN 'HIGH'
        WHEN 3 THEN 'MEDIUM'
        WHEN 4 THEN 'LOW'
    END AS COLONY_NAME
FROM RANKED_ECOLI
ORDER BY ID ASC;