WITH RECURSIVE CTE AS(
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1
    FROM CTE
    WHERE HOUR<23
)
SELECT c.HOUR, COUNT(a.ANIMAL_ID)
FROM CTE c LEFT JOIN ANIMAL_OUTS a
ON c.HOUR=HOUR(a.DATETIME)
GROUP BY c.HOUR
ORDER BY c.HOUR;