SELECT I.NAME AS NAME, I.DATETIME
FROM ANIMAL_INS I
LEFT JOIN ANIMAL_OUTS O -- 아직 입양을 못 간 동물 중
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.DATETIME IS NULL
ORDER BY I.DATETIME ASC
LIMIT 3;-- 결과는 보호 시작일 순으로 조회