SELECT a.id AS ID, COUNT(b.ID) AS CHILD_COUNT
FROM ECOLI_DATA a
LEFT JOIN ECOLI_DATA b
ON a.ID = b.PARENT_ID
GROUP BY a.ID
ORDER BY a.ID ASC;

--# SELECT ID,(
--#     SELECT COUNT(*)
--#     FROM ECOLI_DATA
--#     WHERE PARENT_ID = A.ID
--# ) AS CHILD_COUNT
--# FROM ECOLI_DATA A
--# ORDER BY ID