-- 10월에 대여를 시작한 기록이 있는 '세단 종류' 자동차ID 리스트
-- DISTINCT(CAR_ID)
-- ORDER BY CAR_ID DESC
SELECT DISTINCT(c.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR c
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h
ON c.CAR_ID = h.CAR_ID
WHERE c.CAR_TYPE = '세단' AND MONTH(h.START_DATE)=10
ORDER BY c.CAR_ID DESC;